/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HealthCheck: typeof import('./components/HealthCheck.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouteForm: typeof import('./components/RouteForm.vue')['default']
    RouteResult: typeof import('./components/RouteResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsChart: typeof import('./components/StatsChart.vue')['default']
  }
}
